# -------------------------------------------------
# Plugins file
# -------------------------------------------------

# Dein
# -------------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim' # インストール時のインターフェースを提供


# Util
# -------------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree' # ディレクトリやファイルのツリー表示

# Markup
# -------------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim' # vimでEmmetを使用出来るようにする
## 使用方法を要調査

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides' # インデントに色つけ

[[plugins]]
repo = 'tomtom/tcomment_vim' # コメント拡張
## 使用方法: https://qiita.com/alpaca_taichou/items/211cd62bee84c59ca480

[[plugins]]
repo = 'Townk/vim-autoclose' # 自動でカッコを閉じる
on_i = 1



# Ruby
# -------------------------------------------------
[[plugins]]
repo = 'tpope/vim-rails' # Rails用コマンドを提供するプラグイン

[[plugins]]
repo = 'tpope/vim-endwise' # Ruby向けにendを自動挿入してくれる


# PHP
# -------------------------------------------------

# Git
# -------------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter' # 変更の差分を表示

[[plugins]]
repo = 'tpope/vim-fugitive' # Vim上でgitコマンドを使用できるようにする
# 参考：https://qiita.com/kitagry/items/164abf1518c26def51bf

[[plugins]]
repo = 'tpope/vim-rhubarb'
## 使用方法や設定を要調査


# ---------------------------------------------------------
# 以下未整理
# ---------------------------------------------------------

  [[plugins]]
  repo = 'Shougo/neosnippet.vim'
  [[plugins]]
  repo = 'Shougo/neosnippet-snippets'
  
  [[plugins]]
  repo = 'Shougo/neocomplete.vim'

  [[plugins]]
  repo = 'honza/vim-snippets'
  
  [[plugins]]
  repo = 'ujihisa/neco-look'
  
  [[plugins]]
  repo = 'vim-scripts/AnsiEsc.vim'
  
  [[plugins]]
  repo = 'bronson/vim-trailing-whitespace'

  
  [[plugins]]
  repo = 'Shougo/unite.vim'
  
  [[plugins]]
  repo = 'Shougo/neomru.vim'


  [[plugins]]
  repo = 'mattn/webapi-vim'
  [[plugins]]
  repo = 'hail2u/vim-css3-syntax'
  [[plugins]]
  repo = 'taichouchou2/html5.vim'
  [[plugins]]
  repo = 'kchmck/vim-coffee-script'
  
  # repo = 'marcus/rsense'
  [[plugins]]
  repo = "Shougo/neocomplcache.vim"
  [[plugins]]
  repo = 'Shougo/neocomplcache-rsense.vim'
  [[plugins]]
  repo = 'scrooloose/syntastic'
  [[plugins]]
  repo = 'Townk/vim-autoclose'
  [[plugins]]
  repo = 'scrooloose/syntastic'
  [[plugins]]
  repo = 'itchyny/lightline.vim'
  [[plugins]]
  repo = 'othree/html5.vim'
  
  # repo = 'ryanoasis/vim-devicons'

  [[plugins]]
  repo = 'KazuakiM/neosnippet-snippets'
  [[plugins]]
  repo = 'KazuakiM/vim-qfstatusline'
  [[plugins]]
  repo = 'Shougo/neoinclude.vim'
  [[plugins]]
  repo = 'Shougo/neosnippet.vim'
  # [[plugins]]
  # repo = 'Shougo/vimproc.vim', {'build': 'make'}
  [[plugins]]
  repo = 'thinca/vim-quickrun'
  [[plugins]]
  repo = 'thinca/vim-ref'
  [[plugins]]
  repo = 'vim-scripts/taglist.vim'
  [[plugins]]
  repo = 'osyo-manga/shabadou.vim'
  [[plugins]]
  repo = 'osyo-manga/vim-watchdogs'

  # [[plugins]]
  # repo = 'Shougo/vimshell', { 'rev': '3787e5' }

